<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01_RegresionBrowserStack</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>873c7cba-d9cc-4f8e-b1f0-6d29dfcc5e56</testSuiteGuid>
   <testCaseLink>
      <guid>744031a7-11ba-4fc2-a294-49e44e075d57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05_AOSP_LogInClaveEspecial - BrowserStack</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d295e48f-b026-4c68-b61f-f68a65bfd778</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b25cae8-1481-4031-90fa-fb5f15664faa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db9c9fec-8905-4efd-8c4b-e5c7a6d96eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3147bd2-ebc9-46bc-992f-f6b3c8e97f76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ecc30f1-bce9-4375-8980-1401d527e908</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC02_AOSP_EnvioEpicAEpic</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4548709-76a0-489c-be98-b4f52ceb24af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32a4f84b-d2d3-4751-bc78-cc2d0277cba2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d78fad3-5299-440c-a56a-524fb0a68638</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea2515a4-c110-4f5e-86e2-0858cd146a51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07_AOSP_Retirar</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15b2d2d2-e21f-4331-ac74-62294cd281e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd21d99-6ed2-462c-8538-c2a927af0883</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dde00f26-c6c5-41dd-9dd5-d802357803d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13b5b7ef-385c-4466-ad82-e06fbc43c09b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC08_AOSP_IngresarDinero</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b62a8bc8-c744-4ab2-9680-4e144c7c17d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC03_AOSP_RegistroUsuario - BrowserStack</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe27e49d-d4aa-49ae-8acb-3bac95d43caf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>700327ba-7e1d-4587-8fd1-2e9b170c2216</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd37d1a-276f-4aed-8937-1282c0fdd7e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b28ad10-5f7b-42d6-becb-33d654693720</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af89dbf7-4d93-4a7b-92de-65f63de01d75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>531933d0-c494-4f2c-82ff-90fab3f15963</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
