<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description>Red que se selecciona para hacer la transaccion</description>
   <name>SeleccionRedTronTestnetNile</name>
   <tag></tag>
   <elementGuidId>dabcb710-e59f-46a9-b0aa-c609a1f4d593</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <locator>(//android.widget.TextView[@text=&quot;Llegada estimada: esperar la confirmación de los bloques en la red.&quot;])[1]</locator>
   <locatorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//android.widget.TextView[@text=&quot;Llegada estimada: esperar la confirmación de los bloques en la red.&quot;])[1]</value>
      </entry>
      <entry>
         <key>ID</key>
         <value></value>
      </entry>
      <entry>
         <key>NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>XPATH</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
